<a href="https://colab.research.google.com/github/juanj2007/areglos_11-08-2025/blob/main/arreglos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

25 de aosto de 2025 con matrices ejercicios y operaciones en matrices

In [ ]:
import numpy as np
# crear una matriz 2 * 2 con valores quemados
matriz = np.array([[12, 5], [67, 98]])
print(matriz)

[[12  5]
 [67 98]]


In [ ]:
# crear matrices llenos ceros
matriz=np.zeros((3,3))
print(matriz)
print("\033[34m ---------------------------otra dimesion de matrices---------- \033[0m")
matriz1=np.zeros((2,7))
print(matriz1)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 ---------------------------otra dimesion de matrices---------- 

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]

In [ ]:
# otra forma de imprimiren colores
from rich import print
print("[bold red]Hola[/bold red] mundo!")

Hola mundo!

In [ ]:
import numpy as np
from rich import print
MatrizA=([[2,0,1],[3,0,0],[5,1,1]])
MatrizB=([[1,0,1],[1,2,1],[1,1,0]])
# producto entre matrices
producto=np.dot(MatrizA,MatrizB)
print(f"[yellow]este es el resultado \n {producto}[/yellow]")


este es el resultado 
 [[3 1 2]
 [3 0 3]
 [7 3 6]]

In [ ]:
import numpy as np
MatrizA=([[2,0,1],[3,0,0],[5,1,1]])
# formular de t
MatrizT=np.transpose(MatrizA)
print(f"[yellow]este es el resultado \n {MatrizT}[/yellow]")


este es el resultado 
 [[2 3 5]
 [0 0 1]
 [1 0 1]]

In [8]:
# suma de matrices
import numpy as np
from rich import print
MatrizA=([[2,0,1],[3,0,0],[5,1,1]])
#          2+1
MatrizB=([[1,0,1],[1,2,1],[1,1,0]])
suma=np.add(MatrizA,MatrizB)
print(f"[yellow]este es el resultado \n {suma}[/yellow]")
# otra forma es
MatrizA=([[2,0,1],[3,0,0],[5,1,1]])
MatrizB=([[1,0,1],[1,2,1],[1,1,0]])
# si quiero sumar todos los valores que tiene la matriz
suma=np.sum(MatrizA)
print(f"[yellow]este es el resultado \n {suma}[/yellow]")



este es el resultado 
 [[3 0 2]
 [4 2 1]
 [6 2 1]]

In [1]:
import numpy as np
MatrizA=([[2,0,1],[3,0,0],[5,1,1]])
# formular de t
MatrizT=np.transpose(MatrizA)
print(f"[yellow]este es el resultado \n {MatrizT}[/yellow]")

[yellow]este es el resultado 
 [[2 3 5]
 [0 0 1]
 [1 0 1]][/yellow]


In [2]:
# ejemplo de una matriz  de 3*3 multimplicado por un escalar
import numpy as np
# libreria para los colores
from rich import print

Matriz=np.array([[2,4,5],[4,5,7],[1,0,9]])
escalar=4
MatrizEscalar=escalar*Matriz
print(MatrizEscalar)
# otra forma para manejar escalar
producto=np.multiply(escalar,Matriz)
print(f"[blue]otra forma de operar \n {producto}[/blue]")

[[ 8 16 20]
 [16 20 28]
 [ 4  0 36]]


In [4]:
# import numpy as np
from rich import print
MatrizA=([[2,0,1],[3,0,0],[5,1,1]])
#          2-1
MatrizB=([[1,0,1],[1,2,1],[1,1,0]])

ResultadoResto=np.subtract(MatrizA,MatrizB)
print(f"[yellow]este es el resultado \n {ResultadoResto}[/yellow]")

este es el resultado 
 [[ 1  0  0]
 [ 2 -2 -1]
 [ 4  0  1]]

con ciclos haremos operaciones con escalado

In [10]:
import numpy as np
# creame  de 3*3
Matriz=np.array([[2,4,5],[4,5,7],[1,0,9]])
escalar=4
vector=np.zeros(9)
print(vector)
# c seria columna
# f fila
i=0
# llenar un vecto de 9 posisciones con la matriz de 3*#
for f in range(Matriz.shape[0]):
  for c in range(Matriz.shape[1]):
      a=Matriz[f,c]
      vector[i]=a
      i=i+1

print(vector)
# ahora si con el escalar la matriz
tamano=len(matriz)
print("tamaño matriz", tamano)
for i in range(tamano):
  vector[i]=vector[i]*escalar
print(vector)

# multimplicar el escalar la matriz
#shape es la  que da la dimension o tamaño de la matriz

[0. 0. 0. 0. 0. 0. 0. 0. 0.]

[2. 4. 5. 4. 5. 7. 1. 0. 9.]

Tamaño matriz: 9

[ 8. 16. 20. 16. 20. 28.  4.  0. 36.]

In [12]:
# diagonal superio , e inferior
import numpy as np
tamano=4
# crearemos una matriz de 4*4 para llenarlos de ceros
matriz=np.zeros((tamano,tamano))
print(matriz)
# diagonal superior
#i= fila
#j = columna
for f in range(tamano):
  for c in range(tamano):
    if f<=c:
      matriz[f,c]=1
print(matriz)
# funcion de numpy con diagonal
matriz=np.triu(matriz)
print(f"[#8A4236]{matriz}[/#8A4236]")#


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1. 1. 1.]
 [0. 1. 1. 1.]
 [0. 0. 1. 1.]
 [0. 0. 0. 1.]]

[[1. 1. 1. 1.]
 [0. 1. 1. 1.]
 [0. 0. 1. 1.]
 [0. 0. 0. 1.]]